### ISSUE TITLE
Skalierbarkeit auf kleinen Bildschirmen ist nicht gegeben

### ISSUE THREAD

**Issue by Florz** [ChaosChemnitz/interfug15#4]
Bitte macht die Seite skalierbar für Smartphones.
Egal ob CSS-, JavaScript oder schwarze Magie. Hauptsache es passt auf den Schirm und behält das Design bei Verkleinerung annähernd bei.

**Comment by LittleFox94** [comment]
Ich hätte mich zugewiesen sobald ich echt mal Zeit habe ;)

**Comment by Florz** [comment]
OK, dachte du wolltest das so. Dann mache ich das mal schnell rückgängig...

**Comment by LittleFox94** [comment]
Das Ticket gibts seit 4 Minuten - und es hat mehr Aktivität als die meisten https://github.com/PGPAuth/PGPAuth_Android Tickets :D

**Comment by Florz** [comment]
Ist ja auch ne echt wichtige Sache :p

**Comment by LittleFox94** [comment]
So machen wir mal produktive Kommentare:

Mobil und Desktop gleiches Design?

**Comment by Florz** [comment]
Ja, also der Farbwechsel und das Bild. Das Menü ist halt fraglich. Keine Ahnung ob das Sinnvoll ohne Ausklappmenü geht.

**Comment by LittleFox94** [comment]
Also das Design soll grob so bleiben? Da meinte @drschaf gestern was anderes im IRC

**Comment by gr4yj3d1** [comment]
ich mach es erstmal skalierbar. den rest des designs können wir ja später noch entscheiden...

**Comment by gr4yj3d1** [comment]
Florz: kannst mal nen checkout machen

**Comment by Florz** [comment]
@jdi-li done

**Comment by Florz** [comment]
Danke @jdi-li: b111ca4b7a73f90b749a0182eac034aa64a054f4
