### ISSUE TITLE
<b></b>-Tags haben teilweise keine Wirkung

### ISSUE THREAD

**Issue by Florz** [ChaosChemnitz/interfug15#6]
fetter Text wird nicht immer fett dargestellt (siehe Tickets)
-> tritt mit Google Chrome auf
-> im Firefox gehts

**Comment by MorrisJobke** [comment]
`style="font-weight:bold"`

**Comment by Florz** [comment]
Danke @MorrisJobke, habs in nur drei Anläufen hinbekommen :p
c768ef4c50c5cbe96d63c5fe337cf81c5290e7c1 9d66ee74871d76f48cf412717ed7e9eb56fd757b 5cde83283c995657283e35084f77ca75eb58a81e
